apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: pre-prod
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: v1.19.0
      helm:
        releaseName: rook-ceph
        valueFiles:
        - $values/cluster/pre-production/storage/rookCeph/rookCeph-values.yaml
    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
