apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  members: 3
  type: ReplicaSet
  version: "8.2.6"
  
  security:
    authentication:
      modes: ["SCRAM"]
      
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-auth
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
          
#    - name: app-user
#      db: admin
#      passwordSecretRef:
#        name: mongodb-app-password
#      roles:
#        - name: readWrite
#          db: myapp
          
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    net.compression.compressors: snappy,zstd,zlib
    
  statefulSet:
    spec:
      template:
        spec:
          containers:
#            - name: mongod
            - resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 2000m
                  memory: 4Gi
                
          nodeSelector:
            workload: database
                  
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app: mongodb-svc
                    topologyKey: kubernetes.io/hostname
                    
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: local-path
            resources:
              requests:
                storage: 50Gi
                
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: local-path
            resources:
              requests:
                storage: 10Gi