
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cnpg-cluster-17-053-crowdsec
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  externalSecretName: cnpg-cluster-17-053-crowdsec
  namespaceSelectors:
  - matchLabels:      
      kubernetes.io/metadata.name: cloudnative-pg
  refreshTime: "10s"
  externalSecretSpec:
    refreshInterval: "15s"
    secretStoreRef:
      name: openbao-backend
      kind: ClusterSecretStore
    target:
      name: cnpg-cluster-17-053-crowdsec # K8s secret name
      creationPolicy: Owner
    # To get single key/value(s)
    data:
      - secretKey: username # Key to create in the K8s secret
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: talos-pve/cnpg-cluster-17-053-crowdsec # Path to the secret
          metadataPolicy: None
          property: username # Key of the Vault secret to copy
      - secretKey: password # Key to create in the K8s secret
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: talos-pve/cnpg-cluster-17-053-crowdsec # Path to the secret
          metadataPolicy: None
          property: password # Key of the Vault secret to copy
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster-17-053
  namespace: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instances: 3
  affinity:
    podAntiAffinityType: required
    nodeSelector:
      workload: database
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.5.3 # This is to enable Immich (see Immich deploy to enable db extensions)

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Roles (db usernames)
  managed:
    roles:
    - name: crowdsec
      login: true
      connectionLimit: -1
      ensure: present
      inherit: true
      superuser: false
      passwordSecret:
        name: cnpg-cluster-17-053-crowdsec

  # This is to enable Immich (see Immich deploy to enable db extensions)
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "1024" # This is for Gitlab

  enableSuperuserAccess: true
  # Persistent storage configuration
  storage:
    size: 15Gi
    storageClass: local-path
  walStorage:
    size: 15Gi
    storageClass: local-path

  # Add podMonitor for prometheus monitoring (remember to disable labels scraping in kube-prometheus-stack - podMonitorSelectorNilUsesHelmValues: false)
  monitoring:
    enablePodMonitor: true