apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ferretdb-postgresql-url
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  externalSecretName: ferretdb-postgresql-url
  namespaceSelectors:
  - matchLabels:      
      kubernetes.io/metadata.name: cloudnative-pg
  refreshTime: "10s"
  externalSecretSpec:
    refreshInterval: "15s"
    secretStoreRef:
      name: openbao-backend
      kind: ClusterSecretStore
    target:
      name: ferretdb-postgresql-url # K8s secret name
      creationPolicy: Owner
    # To get single key/value(s)
    data:
      - secretKey: FERRETDB_POSTGRESQL_URL # Key to create in the K8s secret
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: talos-pve/ferretdb-postgresql-url # Path to the secret
          metadataPolicy: None
          property: FERRETDB_POSTGRESQL_URL # Key of the Vault secret to copy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
  namespace: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferretdb
  template:
    metadata:
      labels:
        app: ferretdb
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:2.7.0
          ports:
            - containerPort: 27017
          env:
            - name: FERRETDB_POSTGRESQL_URL
              valueFrom:
                secretKeyRef:
                  name: ferretdb-postgresql-url
                  key: FERRETDB_POSTGRESQL_URL
---
apiVersion: v1
kind: Service
metadata:
  name: ferretdb-service
  namespace: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: ferretdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP