apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: pre-prod
  sources:
    - repoURL: quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: 1.19.2
      helm:
        releaseName: cert-manager
        valueFiles:
        - $values/cluster/pre-production/automation/certManager/certManager-values.yaml
    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
      targetRevision: HEAD
      path: cluster/pre-production/automation/certManager/certManager-post-deploy
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
