apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
#  labels:
#    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: mariadb-root-pwd
spec:
  externalSecretName: mariadb-root-pwd
  namespaceSelectors:
  - matchLabels:      
      kubernetes.io/metadata.name: mariadb-operator
  refreshTime: "10s"
  externalSecretSpec:
    refreshInterval: "15s"
    secretStoreRef:
      name: openbao-backend
      kind: ClusterSecretStore
    target:
      name: mariadb-root-pwd # K8s secret name
      creationPolicy: Owner
    # To get single key/value(s)
    data:
      - secretKey: root-password # Key to create in the K8s secret
        remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: talos-pve/mariadb-root-pwd # Path to the secret
          metadataPolicy: None
          property: root-password # Key of the Vault secret to copy
