apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: pre-prod
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.27.0
      helm:
        releaseName: cloudnative-pg
        valueFiles:
        - $values/cluster/pre-production/databases/cloudnativePG/cloudNativePG-values.yaml
    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
      targetRevision: HEAD
      path: cluster/pre-production/databases/cloudnativePG/clusters
#    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
#      targetRevision: HEAD
#      path: cluster/pre-production/databases/cloudnativePG/databases
    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
      targetRevision: HEAD
      path: cluster/pre-production/databases/cloudnativePG/monitoring
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudnative-pg
  syncPolicy:
#    managedNamespaceMetadata:
#      labels: # The labels to set on the application namespace
#        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
