apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
spec:
  project: pre-prod
  sources:
#    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
#      targetRevision: HEAD
#      path: cluster/pre-production/security/crowdsec/crowdsec-pre-deploy
    - repoURL: https://kubescape.github.io/helm-charts/
      chart: kubescape-operator
      targetRevision: 1.30.4
      helm:
        releaseName: kubescape
#        valueFiles:
#        - $values/cluster/pre-production/security/crowdsec/crowdsec-values.yaml
#    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
#      targetRevision: HEAD
#      ref: values
#    - repoURL: 'https://github.com/urbaman/Talos-Kubernetes-Homelab.git'
#      targetRevision: HEAD
#      path: cluster/pre-production/automation/argoCD/argoCD-post-deploy
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubescape
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/enforce: privileged       
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
