apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <Host>-nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: <Hostname or IP>
  share: <Share>
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}/${pv.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.2
  - bg
  - nolock
  - noatime
  - nointr
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: <Hostname>-csi-nfs-snapshotclass
driver: nfs.csi.k8s.io
deletionPolicy: Delete